import { VideoSlide, TextSlide, ImageDescribedSlide, LeftImageTextSlide } from "../organisms/Slides";
import { TopMenu, HamburgerMenu, Footer } from "../organisms/NavElements";
import peanuts from "../../images/roasted-peanuts-jpg-1656535069.jpg";
import "../../styles/home.css";
const Ships = () => {
    return (
        <>
            <HamburgerMenu />
            <VideoSlide file="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" altimg={peanuts} main="SPACESHIPS" tagline="Ride in Comfort" position="bottomLeft" fit="menu"/>
            <TopMenu homeLink={"#root"} goLabel="FLY WITH US" />
            <TextSlide src={peanuts} subheader="Groundbreaking Technology" header="Ascend Class Ships" paragraph={["At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.", "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo", "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem"]} />
            <div className="bg-black w-full"><div className="w-full max-w-slide mx-auto"><div className="mx-auto w-2/3 bg-white h-[2px]"/></div></div>
            <ImageDescribedSlide src={peanuts} subheader="Next gen" header="leviathan 3 engines" text1="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua" text2="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore" />
            <div className="bg-black w-full"><div className="w-full max-w-slide mx-auto"><div className="mx-auto w-2/3 bg-white h-[2px]"/></div></div>
            <LeftImageTextSlide header="COACHES" subphrase="FIRST CLASS COMFORT" src={peanuts} desc={["Arriving at our futuristic space station, situated in orbit around the moon, you'll be greeted by the ultimate dream destination for adventure seekers and space enthusiasts. Immerse yourself in sheer luxury within the station's most exquisite accommodations, where every detail has been meticulously crafted to provide unrivaled comfort. Feast your eyes on breathtaking views of the moon and Earth from above, while indulging in a wealth of state-of-the-art entertainment facilities. Engage in zero-gravity sports, experience captivating virtual reality simulators, or simply bask in the awe-inspiring surroundings. With artificial gravity ensuring your safety and comfort, you can freely move throughout the station, preparing for awe-inspiring lunar excursions that offer an up-close encounter with the moon's natural wonders. And when it's time to satisfy your taste buds, our station's restaurant and bar await, offering gourmet space cuisine and handcrafted cocktails that will create an unforgettable dining experience. Escape the ordinary and embark on a truly extraordinary adventure with our luxurious ship and space station package, where innovation, comfort, and indulgence merge to redefine the possibilities of space tourism."]} />
            <Footer />
        </>
    )
};
  
export default Ships;